name: sqlite3_simple_example
description: "Demonstrates how to use the sqlite3_simple plugin."
publish_to: 'none'

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  sqlite3_simple:
    path: ../

  cupertino_icons: ^1.0.6
  path: ^1.9.0
  flutter_localizations:
    sdk: flutter
  intl: any
  extended_text: ^15.0.2
  path_provider: ^2.1.5

  sqlite3: ^3.0.0

  sqflite_common_ffi: ^2.4.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true