[versions]
android-library = "8.12.0"
maven-publish = "0.34.0"

[libraries]


[plugins]
android-library = { id = "com.android.library", version.ref = "android-library" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }